package sticksandstones.reference;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

/**
 * Holds the metadata
 */
public class MetaData
{
    /**
     * Setup mod metadata
     *
     * @param metadata
     * @return edited metadata object
     */
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = Reference.NAME + " ";//TODO: give description
        //metadata.url = "";
        //metadata.logoFile = "assets/" + Reference.ID + "/logo.png";
        metadata.version = Reference.V_MAJOR + "." + Reference.V_MINOR + "." + Reference.V_REVIS;
        metadata.authorList = Arrays.asList("blorph", "way2muchnoise", "jafner", "azhDev", "rushmead", "sireSegal", "crummy19", "modmuss50");//TODO: Order?
        //metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
